module.exports = {
    name: 'asanctuary',
    description: "The test pack",
    cards: ["Archlord Zerato","Curse of Anubis","Enchanting Fitting Room","Enemy Controller","King of the Swamp","Monster Gate","Night Assailant","Order to Charge","Spirit of the Pharaoh","The Agent of Force - Mars","The Agent of Judgment - Saturn","Wall of Revealing Light","Zaborg the Thunder Monarch","Amplifier","Beckoning Light","Blowback Dragon","Burst Stream of Destruction","Dark Magic Attack","Des CounterBlow","Emissary of the Afterlife","Gear Golem the Moving Fortress","Ghost Knight of Jackal","Level Limit - Area B","Mazera DeVille","Ninjitsu Art of Transformation","Regenerating Mummy","The Agent of Creation - Venus","The Agent of Wisdom - Mercury","The End of Anubis","The First Sarcophagus","The Sanctuary in the Sky","Vampire Lady","Warrior of Zera","Absorbing Kid from the Sky","Armor Break","Avatar of the Pot","Backfire","Double Coston","Draining Shield","Dust Barrier","Elephant Statue of Disaster","Gogiga Gagagigo","Grave Protector","Labyrinth of Nightmare","Legacy Hunter","Light of Judgment","Needle Burrower","Order to Smash","Protector of the Sanctuary","Rocket Jumper","Solar Flare Dragon","Soul Resurrection","Soul Reversal","Special Hurricane","Spell Economics","Stone Statue of the Aztecs","Talisman of Spell Sealing","Talisman of Trap Sealing","The Second Sarcophagus","The Third Sarcophagus","Theban Nightmare","3-Hump Lacoda","7","Arcane Archer of the Forest","Aswan Apparition","Atomic Firefly","Blessings of the Nile","Delta Attacker","Desert Sunlight","Desertapir","Disc Fighter","Dora of Fate","Earthquake","Elephant Statue of Blessing","Emissary of the Oasis","Fiend Scorpion","Gigobyte","Goblin King","Goblin Thief","Human-Wave Tactics","Judgment of the Desert","KA-2 Des Scissors","Kozaky","Lady Ninja Yae","Legendary Jujitsu Master","Man-Thro' Tro'","Mermaid Knight","Metal Armored Bug","Micro Ray","Mokey Mokey","Mystical Shine Ball","Mystic Wok","Nubian Guard","Opti-Camouflage Armor","Pharaoh's Servant","Pharaonic Protector","Piranha Army","Sand Gambler","Sealmaster Meisei","Solar Ray","Sonic Jammer","Soul-Absorbing Bone Tower","Spirit Caller","Sword of the Soul-Eater","The Kick Man","The Law of Normal","The Unhappy Girl","Thousand Energy","Triangle Power","Two Thousand Needles","Weapon Change","White Magician Pikeru"],
    common: ["3-Hump Lacoda","7","Arcane Archer of the Forest","Aswan Apparition","Atomic Firefly","Blessings of the Nile","Delta Attacker","Desert Sunlight","Desertapir","Disc Fighter","Dora of Fate","Earthquake","Elephant Statue of Blessing","Emissary of the Oasis","Fiend Scorpion","Gigobyte","Goblin King","Goblin Thief","Human-Wave Tactics","Judgment of the Desert","KA-2 Des Scissors","Kozaky","Lady Ninja Yae","Legendary Jujitsu Master","Man-Thro' Tro'","Mermaid Knight","Metal Armored Bug","Micro Ray","Mokey Mokey","Mystical Shine Ball","Mystic Wok","Nubian Guard","Opti-Camouflage Armor","Pharaoh's Servant","Pharaonic Protector","Piranha Army","Sand Gambler","Sealmaster Meisei","Solar Ray","Sonic Jammer","Soul-Absorbing Bone Tower","Spirit Caller","Sword of the Soul-Eater","The Kick Man","The Law of Normal","The Unhappy Girl","Thousand Energy","Triangle Power","Two Thousand Needles","Weapon Change","White Magician Pikeru"],
    uncommon: ["Absorbing Kid from the Sky","Armor Break","Avatar of the Pot","Backfire","Double Coston","Draining Shield","Dust Barrier","Elephant Statue of Disaster","Gogiga Gagagigo","Grave Protector","Labyrinth of Nightmare","Legacy Hunter","Light of Judgment","Needle Burrower","Order to Smash","Protector of the Sanctuary","Rocket Jumper","Solar Flare Dragon","Soul Resurrection","Soul Reversal","Special Hurricane","Spell Economics","Stone Statue of the Aztecs","Talisman of Spell Sealing","Talisman of Trap Sealing","The Second Sarcophagus","The Third Sarcophagus","Theban Nightmare"],
    rare: ["Amplifier","Beckoning Light","Blowback Dragon","Burst Stream of Destruction","Dark Magic Attack","Des CounterBlow","Emissary of the Afterlife","Gear Golem the Moving Fortress","Ghost Knight of Jackal","Level Limit - Area B","Mazera DeVille","Ninjitsu Art of Transformation","Regenerating Mummy","The Agent of Creation - Venus","The Agent of Wisdom - Mercury","The End of Anubis","The First Sarcophagus","The Sanctuary in the Sky","Vampire Lady","Warrior of Zera"],
    epic: ["Archlord Zerato","Curse of Anubis","Enchanting Fitting Room","Enemy Controller","King of the Swamp","Monster Gate","Night Assailant","Order to Charge","Spirit of the Pharaoh","The Agent of Force - Mars","The Agent of Judgment - Saturn","Wall of Revealing Light","Zaborg the Thunder Monarch"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}