module.exports = {
    name: 'custom4',
    description: "The test pack",
    cards: ["Last Will","Card Destruction","Premature Burial","Red Eyes Darkness Dragon","Snatch Steal","Heavy Storm","Creature Swap","Call of the Haunted","Vampire Genesis","Sangan","Zombyra the Dark","Royal Magical Library","Dark Hole","Monster Reborn","Pot of Greed","Witch of the Black Forest","Paladin of White Dragon","Soul Exchange","Megamorph","Nobleman of Crossout","Just Desserts","Luster Dragon","Black Dragon's Chick","Masked Dragon","Ceasefire","Reckless Greed","Interdimensional Matter Transporter","Vampire Lord","Dark Dust Spirit","Pyramid Turtle","Soul-Absorbing Bone Tower","Dark Magician","Summoned Skull","Dark Blade","Wall of Illusion","Kuriboh","Sonic Bird","Black Luster Soldier","Black Luster Ritual","Fissure","Change of Heart","Axe of Despair","Mystical Space Typhoon","Swords of Revealing Light","Trap Hole","Waboku","Spellbinding Circle","Raigeki Break","Blue Eyes White Dragon","La Jinn the Mystical Genie of the Lamp","Kaiser Sea Horse","Lord of D.","Mystic Tomato","White Dragon Ritual","The Flute of Summoning Dragon","Tribute to the Doomed","Rush Recklessly","Fairy Meteor Crush","Shadow Spell","Dust Tornado","Red-Eyes Black Dragon","Armed Dragon LV3","Armed Dragon Lv5","Element Dragon","Stamping Destruction","Reload","Dragon's Rage","Spirit Reaper","Ryu Kokki","Vampire Lady","Regenerating Mummy","Great Angus","Mystical Elf","Feral Imp","Winged Dragon, Guardian of the Fortress #1","Beaver Warrior","Celtic Guardian","Gaia the Fierce Knight","Great White","Giant Soldier of Stone","Mystic Clown","Neo the Magic Swordsman","Gazelle the King of Mythical Beasts","Warrior Dai Grepher","Man-Eater Bug","Giant Rat","Dian Keto the Cure Master","The Reliable Guardian","Malevolent Nuzzler","Magic Jammer","Seven tools of the Bandit","The Eye of Truth","Backup Soldier","Disappear","Battle Ox","Koumori Dragon","Rogue Doll","Kojikocy","Uraby","Mystic Horseman","Ryu-Kishin Powered","Skull Red Bird","Hyozanryu","Opticlops","The Dragon Dewlling in the Cave","Luster Dragon #2","Mysterious Puppeteer","Trap Master","Hane-Hane","Spirit Ryu","Ookazi","De-Spell","The Inexperianced Spy","Mountain","Gift of the Mystical Elf","Light of Intervention","Jar of Greed","Riryoku Field","Burst Breath"],
    common: ["Mystical Elf","Feral Imp","Winged Dragon, Guardian of the Fortress #1","Beaver Warrior","Celtic Guardian","Gaia the Fierce Knight","Great White","Giant Soldier of Stone","Mystic Clown","Neo the Magic Swordsman","Gazelle the King of Mythical Beasts","Warrior Dai Grepher","Man-Eater Bug","Giant Rat","Dian Keto the Cure Master","The Reliable Guardian","Malevolent Nuzzler","Magic Jammer","Seven tools of the Bandit","The Eye of Truth","Backup Soldier","Disappear","Battle Ox","Koumori Dragon","Rogue Doll","Kojikocy","Uraby","Mystic Horseman","Ryu-Kishin Powered","Skull Red Bird","Hyozanryu","Opticlops","The Dragon Dewlling in the Cave","Luster Dragon #2","Mysterious Puppeteer","Trap Master","Hane-Hane","Spirit Ryu","Ookazi","De-Spell","The Inexperianced Spy","Mountain","Gift of the Mystical Elf","Light of Intervention","Jar of Greed","Riryoku Field","Burst Breath"],
    uncommon: ["Dark Magician","Summoned Skull","Dark Blade","Wall of Illusion","Kuriboh","Sonic Bird","Black Luster Soldier","Black Luster Ritual","Fissure","Change of Heart","Axe of Despair","Mystical Space Typhoon","Swords of Revealing Light","Trap Hole","Waboku","Spellbinding Circle","Raigeki Break","Blue Eyes White Dragon","La Jinn the Mystical Genie of the Lamp","Kaiser Sea Horse","Lord of D.","Mystic Tomato","White Dragon Ritual","The Flute of Summoning Dragon","Tribute to the Doomed","Rush Recklessly","Fairy Meteor Crush","Shadow Spell","Dust Tornado","Red-Eyes Black Dragon","Armed Dragon LV3","Armed Dragon Lv5","Element Dragon","Stamping Destruction","Reload","Dragon's Rage","Spirit Reaper","Ryu Kokki","Vampire Lady","Regenerating Mummy","Great Angus"],
    rare: ["Sangan","Zombyra the Dark","Royal Magical Library","Dark Hole","Monster Reborn","Pot of Greed","Witch of the Black Forest","Paladin of White Dragon","Soul Exchange","Megamorph","Nobleman of Crossout","Just Desserts","Luster Dragon","Black Dragon's Chick","Masked Dragon","Ceasefire","Reckless Greed","Interdimensional Matter Transporter","Vampire Lord","Dark Dust Spirit","Pyramid Turtle","Soul-Absorbing Bone Tower"],
    epic: ["Last Will","Card Destruction","Premature Burial","Red Eyes Darkness Dragon","Snatch Steal","Heavy Storm","Creature Swap","Call of the Haunted","Vampire Genesis"],
    price: 125,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}

