module.exports = {
    name: 'custom5',
    description: "The test pack",
    cards: ["Giant Trunade","Card of Safe Return","Torrential Tribute","Infernal Flame Emperor","Ocean Dragon Lord - Neo-Daedalus","Tribe Infecting Virus","Gravity Bind","Cyber-Stein","Return from the Different Dimension","Double-Coston","Book of Life","Call of the Mummy","Compulsory Evacuation Device","Thestalos the Firestorm Monarch","Levia-Dragon - Daedalus","Mobius the Frost Monarch","A Legendary Ocean","Salvage","Fusion Gate","King of the Swamp","Needle Worm","Kycoo the Ghost Destroyer","Bazoo the Soul-Eater","Widespread Ruin","Sage's Stone","Silent Swordsman LV7","Kaibaman","Blue-Eyes Shining Dragon","Sorceror of Dark Magic","Theinen the Great Sphinx","Andro Sphinx","Sphinx Teleia","Blazing Inpachi","Inferno","Solar Flare Dragon","Ultimate Baseball Kid","Raging Flame Sprite","Gaia Soul the Combustable Collective","Level Limit Area B","Necklace of Command","7 Colored Fish","Sea Serpent Warrior of Darkness","Fenrir","Mermaid Knight","Unshaven Angler","Hammer Shot","Tornado Wall","Total Defense Shogun","Blade Knight","Command Knight","Swift Gaia the Fierce Knight","Big Shield Gardna","Goddess with the Third Eye","Jowgen the Spiritualist","Destruction Punch","Beastking of the Swamp","Mystical Sheep #1","Versago the Destroyer","Toon Gemini Elf","Toon Goblin Attack Force","Slate Warrior","Dark Sage","Dark Magician Knight","Knight's Title","Emes the Infinity","D.D. Assailant","Abyss Soldier","Mind Control","Pyrimid of Light","Rare Metal Dragon","Peten the Dark Clown","Inferno Tempest","Twin-Headed Behemoth","The Graveyard in the Fourth Dimension","The Dragon's Bead","Trap Jammer","Curse of Anubis","Master Kyonshee","Despair from the Dark","UFO Turtle","Little Chimera","Molten Zombie","Fox Fire","Molten Destruction","Dark Room of Nightmare","Meteor of Destruction","Spell Shield Type-8","Backfire","Space Mombo","Mother Grizzly","Star Boy","Amphibious Bugroth MK-3","Creeping Doom Manta","Big Wave Small Wave","Xing Zhen Hu","Insect Queen","Archfiend of Gilfer","Machine King","Restructer Revolution","Sengenjin","Lord of the Lamp","Greenkappa","Luminous Soldier","Magical Thorn","Trap of Board Eraser","Tornado Bird","Curse of Royal","Winged Sage Falcos","Dark Designator","Fairy King Truesdale","Cipher Soldier","Sebek's Blessing","Sword of Dragon Soul","Twinheaded Beast","Inferno Hammer","Teva","Watapon","Familiar Knight","D. Tribe"],
    common: ["Twin-Headed Behemoth","The Graveyard in the Fourth Dimension","The Dragon's Bead","Trap Jammer","Curse of Anubis","Master Kyonshee","Despair from the Dark","UFO Turtle","Little Chimera","Molten Zombie","Fox Fire","Molten Destruction","Dark Room of Nightmare","Meteor of Destruction","Spell Shield Type-8","Backfire","Space Mombo","Mother Grizzly","Star Boy","Amphibious Bugroth MK-3","Creeping Doom Manta","Big Wave Small Wave","Xing Zhen Hu","Insect Queen","Archfiend of Gilfer","Machine King","Restructer Revolution","Sengenjin","Lord of the Lamp","Greenkappa","Luminous Soldier","Magical Thorn","Trap of Board Eraser","Tornado Bird","Curse of Royal","Winged Sage Falcos","Dark Designator","Fairy King Truesdale","Cipher Soldier","Sebek's Blessing","Sword of Dragon Soul","Twinheaded Beast","Inferno Hammer","Teva","Watapon","Familiar Knight","D. Tribe"],
    uncommon: ["Blazing Inpachi","Inferno","Solar Flare Dragon","Ultimate Baseball Kid","Raging Flame Sprite","Gaia Soul the Combustable Collective","Level Limit Area B","Necklace of Command","7 Colored Fish","Sea Serpent Warrior of Darkness","Fenrir","Mermaid Knight","Unshaven Angler","Hammer Shot","Tornado Wall","Total Defense Shogun","Blade Knight","Command Knight","Swift Gaia the Fierce Knight","Big Shield Gardna","Goddess with the Third Eye","Jowgen the Spiritualist","Destruction Punch","Beastking of the Swamp","Mystical Sheep #1","Versago the Destroyer","Toon Gemini Elf","Toon Goblin Attack Force","Slate Warrior","Dark Sage","Dark Magician Knight","Knight's Title","Emes the Infinity","D.D. Assailant","Abyss Soldier","Mind Control","Pyrimid of Light","Rare Metal Dragon","Peten the Dark Clown","Inferno Tempest"],
    rare: ["Double-Coston","Book of Life","Call of the Mummy","Compulsory Evacuation Device","Thestalos the Firestorm Monarch","Levia-Dragon - Daedalus","Mobius the Frost Monarch","A Legendary Ocean","Salvage","Fusion Gate","King of the Swamp","Needle Worm","Kycoo the Ghost Destroyer","Bazoo the Soul-Eater","Widespread Ruin","Sage's Stone","Silent Swordsman LV7","Kaibaman","Blue-Eyes Shining Dragon","Sorceror of Dark Magic","Theinen the Great Sphinx","Andro Sphinx","Sphinx Teleia"],
    epic: ["Giant Trunade","Card of Safe Return","Torrential Tribute","Infernal Flame Emperor","Ocean Dragon Lord - Neo-Daedalus","Tribe Infecting Virus","Gravity Bind","Cyber-Stein","Return from the Different Dimension"],
    price: 125,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}

