module.exports = {
    name: 'demonstuff',
    description: "The test pack",
    cards: ["Bean Soldier","Blue Medicine","Call of the Grave","Cockroach Knight","Corroding Shark","Cyber Soldier of Darkworld","Dancing Elf","Dharma Cannon","Fairy's Gift","Faith Bird","Fyling Penguin","Garoozis","Giant Flea","Goblin Fan","Hercules Beetle","Kuwagata a","Kwager Hercules","Megasonic Eye","Novox's Prayer","Oscillo Hero","Parrot Dragon","Patrol Robo","Queen of Autumn Leaves","Raimei","Revival of Dokurorider","Shining Friendship","Sky Dragon","Slime Toad","Sonic Maid","Spirit of the Books","Stuffed Animal","Takriminos","Takuhee","The Judgement Hand","The Statue of Easter Island","Three-Legged Zombies","Tiger Axe","Turtle Bird","Turu-Purun","Ushi Oni","Warrior of Tradition","Water Magician","Wattkid","White Hole","Winged Dragon, Guardian of the Fortress #2","Wodan the Resident of the Forest","Wow Warrior","Yamadron","Yaranzo","Beautiful Headhuntress","Berfomet","Burning Spear","Chimera the Flying Mythical Beast","Crawling Dragon #2","Dark-Piercing Light","Dokurorider","Dragon Seeker","Elf's Light","Exile of the Wicked","Giant Red Seasnake","Gust Fan","MetalZoa","Mikazukinoyaiba","Millennium Shield","Seiyaryu","Skull Guardian","Soul of the Pure","Steel Shell","Two-headed King Rex","Zoa","Acid Trap Hole","Beastking of the Swamps","Black Luster Ritual","Cosmo Queen","Goddess of Whim","Goddess with the Third Eye","Graceful Charity","Harpie's Feather Duster","Mystical Sheep #1","Salamandra","Thousand Knives","Versago the Destroyer","Anti-Spell Fragrence","Black Luster Soldier","Blue Eyes Ultimate Dragon","Exchange","Harpie's Pet Dragon","Mechanicalchaser","Morphing Jar","Ninja Grandmaster Sasuke","Sinister Serpent"],
    common: ["Bean Soldier","Blue Medicine","Call of the Grave","Cockroach Knight","Corroding Shark","Cyber Soldier of Darkworld","Dancing Elf","Dharma Cannon","Fairy's Gift","Faith Bird","Fyling Penguin","Garoozis","Giant Flea","Goblin Fan","Hercules Beetle","Kuwagata a","Kwager Hercules","Megasonic Eye","Novox's Prayer","Oscillo Hero","Parrot Dragon","Patrol Robo","Queen of Autumn Leaves","Raimei","Revival of Dokurorider","Shining Friendship","Sky Dragon","Slime Toad","Sonic Maid","Spirit of the Books","Stuffed Animal","Takriminos","Takuhee","The Judgement Hand","The Statue of Easter Island","Three-Legged Zombies","Tiger Axe","Turtle Bird","Turu-Purun","Ushi Oni","Warrior of Tradition","Water Magician","Wattkid","White Hole","Winged Dragon, Guardian of the Fortress #2","Wodan the Resident of the Forest","Wow Warrior","Yamadron","Yaranzo"],
    uncommon: ["Beautiful Headhuntress","Berfomet","Burning Spear","Chimera the Flying Mythical Beast","Crawling Dragon #2","Dark-Piercing Light","Dokurorider","Dragon Seeker","Elf's Light","Exile of the Wicked","Giant Red Seasnake","Gust Fan","MetalZoa","Mikazukinoyaiba","Millennium Shield","Seiyaryu","Skull Guardian","Soul of the Pure","Steel Shell","Two-headed King Rex","Zoa"],
    rare: ["Acid Trap Hole","Beastking of the Swamps","Black Luster Ritual","Cosmo Queen","Goddess of Whim","Goddess with the Third Eye","Graceful Charity","Harpie's Feather Duster","Mystical Sheep #1","Salamandra","Thousand Knives","Versago the Destroyer"],
    epic: ["Anti-Spell Fragrence","Black Luster Soldier","Blue Eyes Ultimate Dragon","Exchange","Harpie's Per Dragon","Mechanicalchaser","Morphing Jar","Ninja Grandmaster Sasuke","Sinister Serpent"],
    price: 125,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}