module.exports = {
    name: 'custom1',
    description: "The test pack",
    cards: ["Ancient Elf","Ryu-Kishin","Ancient Telescope","Shield & Sword","Ansatsu","Skull Red Bird","Armored Lizard","Sogen","Baby Dragon","Sorcerer of the Doomed","Baron of the Fiend Sword","Swordsman of Landstar","Beaver Warrior","Terra the Terrible","Block Attack","The Inexperienced Spy","Book of Secret Arts","The Reliable Guardian","Castle Walls","The Stern Mystic","Celtic Guardian","The Wicked Worm Beast","Claw Reacher","D. Human","Unknown Warrior of Fiend","Dark Assailant","Uraby","Dark Energy","Winged Dragon, Guardian of the Fortress #1","Dark Titan of Terror","Witty Phantom","De-Spell","Destroyer Golem","Doma the Angel of Silence","Dragon Treasure","Eternal Rest","Fake Trap","Feral Imp","Flame Manipulator","Flame Swordsman","Gyakutenno Megami","Hitotsu-Me Giant","Karate Man","Kojikocy","Koumori Dragon","Magical Ghost","Mammoth Graveyard","Masaki the Legendary Swordsman","Master & Expert","Mountain","Mysterious Puppeteer","Mystic Clown","Mystic Horseman","Ogre of the Black Shadow","Pale Beast","Princess of Tsurugi","Remove Trap","Rude Kaiser","7 Colored Fish","Battle Ox","Big Eye","Curse of Dragon","Darkfire Soldier #1","Dian Keto the Cure Master","Dragon Capture Jar","Dragon Zombie","Gearfried the Iron Knight","Giant Soldier of Stone","Great White","Invigoration","Island Turtle","Judge Man","La Jinn the Mystical Genie of the Lamp","Malevolent Nuzzler","Man-Eating Treasure Chest","Milus Radiant","Mystical Elf","Neo the Magic Swordsman","Ookazi","Red-Eyes Black Metal Dragon","Reinforcements","Reverse Trap","Rogue Doll","Ryu-Kishin Powered","Sky Scout","Spirit of the Harp","Sword of Dark Destruction","Time Wizard","Trap Master","Two-Pronged Attack","White Magical Hat","Thousand Dragon","Blue-Eyes White Dragon","Dark Hole","Dark Magician","Fissure","Gaia the Fierce Knight","Giant Trunade","Hane-Hane","Just Desserts","Lord of D.","Maha Vailo","Man-Eater Bug","Metalmorph","Penguin Soldier","Red-Eyes B. Dragon","Sangan","Scapegoat","Seven Tools of the Bandit","Soul Exchange","The Flute of Summoning Dragon","Trap Hole","Waboku","Wall of Illusion","Card Destruction","Change of Heart","Last Will","Magician of Faith","Monster Reborn","Summoned Skull","Ultimate Offering","Valkyrion the Magna Warrior"],
    common: ["Ancient Elf","Ryu-Kishin","Ancient Telescope","Shield & Sword","Ansatsu","Skull Red Bird","Armored Lizard","Sogen","Baby Dragon","Sorcerer of the Doomed","Baron of the Fiend Sword","Swordsman of Landstar","Beaver Warrior","Terra the Terrible","Block Attack","The Inexperienced Spy","Book of Secret Arts","The Reliable Guardian","Castle Walls","The Stern Mystic","Celtic Guardian","The Wicked Worm Beast","Claw Reacher","D. Human","Unknown Warrior of Fiend","Dark Assailant","Uraby","Dark Energy","Winged Dragon, Guardian of the Fortress #1","Dark Titan of Terror","Witty Phantom","De-Spell","Destroyer Golem","Doma the Angel of Silence","Dragon Treasure","Eternal Rest","Fake Trap","Feral Imp","Flame Manipulator","Flame Swordsman","Gyakutenno Megami","Hitotsu-Me Giant","Karate Man","Kojikocy","Koumori Dragon","Magical Ghost","Mammoth Graveyard","Masaki the Legendary Swordsman","Master & Expert","Mountain","Mysterious Puppeteer","Mystic Clown","Mystic Horseman","Ogre of the Black Shadow","Pale Beast","Princess of Tsurugi","Remove Trap","Rude Kaiser"],
    uncommon: ["7 Colored Fish","Battle Ox","Big Eye","Curse of Dragon","Darkfire Soldier #1","Dian Keto the Cure Master","Dragon Capture Jar","Dragon Zombie","Gearfried the Iron Knight","Giant Soldier of Stone","Great White","Invigoration","Island Turtle","Judge Man","La Jinn the Mystical Genie of the Lamp","Malevolent Nuzzler","Man-Eating Treasure Chest","Milus Radiant","Mystical Elf","Neo the Magic Swordsman","Ookazi","Red-Eyes Black Metal Dragon","Reinforcements","Reverse Trap","Rogue Doll","Ryu-Kishin Powered","Sky Scout","Spirit of the Harp","Sword of Dark Destruction","Time Wizard","Trap Master","Two-Pronged Attack","White Magical Hat","Thousand Dragon"],
    rare: ["Blue-Eyes White Dragon","Dark Hole","Dark Magician","Fissure","Gaia the Fierce Knight","Giant Trunade","Hane-Hane","Just Desserts","Lord of D.","Maha Vilo","Man-Eater Bug","Metalmorph","Penguin Soldier","Red-Eyes B. Dragon","Scapegoat","Seven Tools of the Bandit","Soul Exchange","The Flute of Summoning Dragon","Trap Hole","Waboku","Wall of Illusion"],
    epic: ["Card Destruction","Change of Heart","Last Will","Magician of Faith","Monster Reborn","Summoned Skull","Ultimate Offering","Valkyrion the Magna Warrior","Sangan"],
    price: 125,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}

