module.exports = {
    name: 'custom6',
    description: "The test pack",
    cards: ["Breaker the Magical Warrior","Skilled Dark Magician","Last Will","Silent Magician LV8","Gilford the Legend","Snatch Steal","Giant Trunade","Heavy Storm","Reinforcements of the Army","D.D. Warrior Lady","Scapegoat","Soul Exchange","Toon Table of Contents","Fusion Sage","Yamata Dragon","Silent Magician LV4","Magician's Circle","Swift Gaia the Fierce Knight","Marauding Captain","Exiled Force","Call of the Haunted","Gilford the Lightning","Vorse Raider","Gearfried the Swordmaster","Amazoness Swords Woman","Chaos Command Magician","Skilled White Magician","Armed Samurai - Ben Kei","Toon Cannon Soldier","Royal Decree","Spear Dragon","Airknight Parshath","Susa Soldier","Emergency Provisions","Blast with Chain","Warrior of the Wasteland","Dark Blade","Obnoxious Celtic Guard","Command Knight","Mataza the Zapper","Mystic Swordsman LV2","Mystic Swordsman LV4","Ninja Grandmaster Sasuke","The Warrior Returning Alive","Fusion Sword Murasame Blade","Wicked-Breaking Flamberge - Baou","Reload","Lightning Vortex","Dark Magician Girl","Des Volstgalph","Warrior Elimination","Fortress Whale","Luminous Soldier","Goblin Attack Force","Fortress Whale's Oath","Wall of Illusion","Haniwa","Prisman","Millennium Golem","Dig Beak","Nekogal #2","Firewing Pegasus","Restructer Revolution","Dark Balter the Terrible","Ryu Senshi","Fiend Skull Dragon","Last Turn","Archfiend Marmot of Nefariousness","Sleeping Lion","Nekogal #1","Burglar","Clown Zombie","Gearfried the Iron Knight","D.D. Warrior","Zoa","Acid Rain","Divine Sword - Phoenix Blade","Mystical Space Typhoon","Lightning Blade","Fairy of the Spring","Swords of Concealing Light","Release Restraint","Magic Jammer","Thunder Nyan Nyan","Exarion Universe","Rocket Warrior","Panther Warrior"],
    common: ["Des Volstgalph","Warrior Elimination","Fortress Whale","Luminous Soldier","Goblin Attack Force","Fortress Whale's Oath","Wall of Illusion","Haniwa","Prisman","Millennium Golem","Dig Beak","Nekogal #2","Firewing Pegasus","Restructer Revolution","Dark Balter the Terrible","Ryu Senshi","Fiend Skull Dragon","Last Turn","Archfiend Marmot of Nefariousness","Sleeping Lion","Nekogal #1","Burglar","Clown Zombie","Gearfried the Iron Knight","D.D. Warrior","Zoa","Acid Rain","Divine Sword - Phoenix Blade","Mystical Space Typhoon","Lightning Blade","Fairy of the Spring","Swords of Concealing Light","Release Restraint","Magic Jammer","Thunder Nyan Nyan","Exarion Universe","Rocket Warrior","Panther Warrior"],
    uncommon: ["Gearfried the Swordmaster","Amazoness Swords Woman","Chaos Command Magician","Skilled White Magician","Armed Samurai - Ben Kei","Toon Cannon Soldier","Royal Decree","Spear Dragon","Airknight Parshath","Susa Soldier","Emergency Provisions","Blast with Chain","Warrior of the Wasteland","Dark Blade","Obnoxious Celtic Guard","Command Knight","Mataza the Zapper","Mystic Swordsman LV2","Mystic Swordsman LV4","Ninja Grandmaster Sasuke","The Warrior Returning Alive","Fusion Sword Murasame Blade","Wicked-Breaking Flamberge - Baou","Reload","Lightning Vortex","Dark Magician Girl"],
    rare: ["D.D. Warrior Lady","Scapegoat","Soul Exchange","Toon Table of Contents","Fusion Sage","Yamata Dragon","Silent Magician LV4","Magician's Circle","Swift Gaia the Fierce Knight","Marauding Captain","Exiled Force","Call of the Haunted","Gilford the Lightning","Vorse Raider"],
    epic: ["Breaker the Magical Warrior","Skilled Dark Magician","Last Will","Silent Magician LV8","Gilford the Legend","Snatch Steal","Giant Trunade","Heavy Storm","Reinforcements of the Army"],
    price: 125,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}

