module.exports = {
    name: 'dark',
    description: "The test pack",
    cards: ["Dark Paladin","Dark Magician","Dark Magician","Magical Marionette","Summoned Skull","Breaker the Magical Warrior","Dark Hole","Call of the Haunted","Mirror Force","Magic Cylinder","Pitch-Black Power Stone","Threatening Roar","Skilled Dark Magician","Skilled Dark Magician","Apprentice Magician","Apprentice Magician","Rush Recklessly","Negate Attack","Sakuretsu Armor","Seven Tools of the Bandit","Trap Hole","Stray Lambs","Cost Down","Polymerization","Polymerization","Pot of Greed","Monster Reborn","Mystical Space Typhoon","Swords of Revealing Light","Malevolent Nuzzler","Mystic Tomato","Mystic Tomato","Pitch-Black Warwolf","Double Coston","Double Coston","Archfiend Soldier","Mad Dog of Darkness","The Dark - Hex-Sealed Fusion","The Dark - Hex-Sealed Fusion","Old Vindictive Magician","Kuriboh"],
    common: ["Ancient Brain","Ancient Elf","Ancient Lizard Warrior","Armored Lizard","Bickuribox","Bladefly","Blast Juggler","Block Attack","Blue-Winged Crown","Bottom Dweller","Cannon Soldier","Cyber Saurus","Dark Elf","Deepsea Shark","Destroyer Golem","Disk Magician","Dragon Piper","Dream Clown","Electric Lizard","Empress Judge","Fake Trap","Feral Imp","Flame Cerberus","Garnecia Elefantis","Gazelle the King of Mythical Beasts","Germ Infection","Giga-Tech Wolf","Giltia the D. Knight","Ground Attacker Bugroth","Guardian of the Labyrinth","Harpie Lady","Hibikime","Hoshiningen","Hunter Spider","Hyosube","Illusionist Faceless Mage","Insect Soldiers of the Sky","Jinzo #7","Kaminari Attack","Killer Needle","Labyrinth Tank","Lady of Faith","Larvae Moth","Launcher Spider","Leghul","Leogun","Little Chimera","Masked Sorcerer","Mega Thunderball","Milus Radiant","Morinphen","Muka Muka","Mushroom Man #2","Musician King","Mystic Lamp","Niwatori","Ocubeam","Ooguchi","Pale Beast","Paralyzing Potion","Petit Moth","Prevent Rat","Princess of Tsurugi","Protector of the Throne","Punished Eagle","Queen's Double","Rainbow Flower","Ring of Magnetism","Roaring Ocean Snake","Robbin' Goblin","Rock Ogre Grotto #1","Ryu-Kishin Powered","Saggi the Dark Clown","Shadow Ghoul","Shield & Sword","Skull Knight","Star Boy","Steel Scorpion","Stim-Pack","Sword of Deep-Seated","Tainted Wisdom","The Bistro Butcher","The Immortal of Thunder","The Little Swordsman of Aile","The Unhappy Maiden","Tongyo","Trent","Twin-Headed Thunder Dragon","Water Omotics","Winged Dragon, Guardian of the Fortress #1","Witch's Apprentice","Yado Karu"],
    uncommon: ["7 Colored Fish","Armored Zombie","Baby Dragon","Battle Steer","Blackland Fire Dragon","Castle of Dark Illusions","Catapult Turtle","Cocoon of Evolution","Crass Clown","Crawling Dragon","Doma the Angel of Silence","Elegant Egotist","Thousand Dragon","Great Moth","Jellyfish","Jirai Gumo","King of Yamimakai","Kojikocy","Kuriboh","Lava Battleguard","Mystic Horseman","Pumpking the King of Ghosts","Rabid Horseman","Share the Pain","Soul Release","Swamp Battleguard","The Cheerful Coffin","Thunder Dragon","Time Wizard","Tremendous Fire","White Magical Hat"],
    rare: ["Big Eye","B. Skull Dragon","Share the Pain","Gate Guardian","Harpie Lady Sisters","Horn of Heaven","Kazejin","Magic Jammer","Mask of Darkness","Sanga of the Thunder","Seven Tools of the Bandit","Suijin","Tribute to the Doomed"],
    epic: ["Barrel Dragon","Change of Heart","Heavy Storm","Magician of Faith","Mirror Force","Sangan","Solemn Judgment","Summoned Skull","Witch of the Black Forest"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}