module.exports = {
    name: 'dcrisis',
    description: "The test pack",
    cards: ["Blast Held by a Tribute","D.D. Warrior Lady","Exodia Necross","Final Countdown","Judgment of Anubis","Reflect Bounder","Shinato, King of a Higher Plane","Skill Drain","Tsukuyomi","Vampire Lord","Archfiend Soldier","Bezerk Dragon","Cost Down","Despair from the Dark","Frozen Soul","Gravity Axe - Grarl","Great Maju Garzett","Guardian Grarl","Interdimensional Matter Transporter","Kaiser Glider","Mefist the Infernal General","Mirage Knight","Ojama Trio","Pandemonium","Sakuretsu Armor","Skull Archfiend of Lightning","Terrorking Archfiend","Agido","Archfiend's Oath","Archfiend's Roar","Arsenal Summoner","Blindly Loyal Goblin","Butterfly Dagger- Elma","Cetus of Dagla","Checkmate","Dark Flare Knight","Dark Master - Zorc","Dark Scorpion - Chick the Yellow","Dark Scorpion - Gorg the Strong","Dark Scorpion - Meanae the Thron","Des Feral Imp","Different Dimension Dragon","Dragged Down into the Grave","Falling Down","Fear from the Dark","Gagagigo","Guardian Baou","Guardian Ceal","Guardian Kay'est","Guardian Tryce","Iron Blacksmith Kotetsu","Legendary Flame Lord","Maju Garzett","Mudora","Nin-Ken Dog","Really Eternal Rest","Rod of the Mind's Eye","Shadowknight Archfiend","Shinato's Ark","Shooting Star Bow - Ceal","Spell Reproduction","Twin Swords of Flashing Light - Tryce","Wicked-Breaking Flamberge - Baou","A Deal with Dark Ruler","Acrobat Monkey","Altar for Tribute","Arsenal Robber","Battle Footballer","Battle-Scarred","Contact with Exodia","Contact with the Abyss","Contact with the Dark Master","Cyber Raider","D.D. Trainer","Dark Scorpion Combination","Darkbishop Archfiend","Dice Re-Roll","Different Dimension Gate","Fairy of the Spring","Final Attack Orders","Goblin of Greed","Guardian Elma","Gyaku-Gire Panda","Incandescent Ordeal","InfernalQueen Archfiend","Kelbek","Keldo","Little-Winguard","Metallizing Parasite - Lumanite","Morale Boost","Mustering of the Dark Scorpions","Non-Spellcasting Area","Ojama Green","Outstanding Dog Marron","Pandemonium Watchbear","Precious Cards from Beyond","Ray of Hope","Rod of Silence - Kay'est","Sasuke Samurai #2","Spell Vanishing","Staunch Defender","Thousand Needles","Token Thanksgiving","Vilepawn Archfiend","Zolga"],
    common: ["A Deal with Dark Ruler","Acrobat Monkey","Altar for Tribute","Arsenal Robber","Battle Footballer","Battle-Scarred","Contact with Exodia","Contact with the Abyss","Contact with the Dark Master","Cyber Raider","D.D. Trainer","Dark Scorpion Combination","Darkbishop Archfiend","Dice Re-Roll","Different Dimension Gate","Fairy of the Spring","Final Attack Orders","Goblin of Greed","Guardian Elma","Gyaku-Gire Panda","Incandescent Ordeal","InfernalQueen Archfiend","Kelbek","Keldo","Little-Winguard","Metallizing Parasite - Lumanite","Morale Boost","Mustering of the Dark Scorpions","Non-Spellcasting Area","Ojama Green","Outstanding Dog Marron","Pandemonium Watchbear","Precious Cards from Beyond","Ray of Hope","Rod of Silence - Kay'est","Sasuke Samurai #2","Spell Vanishing","Staunch Defender","Thousand Needles","Token Thanksgiving","Vilepawn Archfiend","Zolga"],
    uncommon: ["Agido","Archfiend's Oath","Archfiend's Roar","Arsenal Summoner","Blindly Loyal Goblin","Butterfly Dagger- Elma","Cetus of Dagla","Checkmate","Dark Flare Knight","Dark Master - Zorc","Dark Scorpion - Chick the Yellow","Dark Scorpion - Gorg the Strong","Dark Scorpion - Meanae the Thron","Des Feral Imp","Different Dimension Dragon","Dragged Down into the Grave","Falling Down","Fear from the Dark","Gagagigo","Guardian Baou","Guardian Ceal","Guardian Kay'est","Guardian Tryce","Iron Blacksmith Kotetsu","Legendary Flame Lord","Maju Garzett","Mudora","Nin-Ken Dog","Really Eternal Rest","Rod of the Mind's Eye","Shadowknight Archfiend","Shinato's Ark","Shooting Star Bow - Ceal","Spell Reproduction","Twin Swords of Flashing Light - Tryce","Wicked-Breaking Flamberge - Baou"],
    rare: ["Archfiend Soldier","Bezerk Dragon","Cost Down","Despair from the Dark","Frozen Soul","Gravity Axe - Grarl","Great Maju Garzett","Guardian Grarl","Interdimensional Matter Transporter","Kaiser Glider","Mefist the Infernal General","Mirage Knight","Ojama Trio","Pandemonium","Sakuretsu Armor","Skull Archfiend of Lightning","Terrorking Archfiend"],
    epic: ["Blast Held by a Tribute","D.D. Warrior Lady","Exodia Necross","Final Countdown","Judgment of Anubis","Reflect Bounder","Shinato, King of a Higher Plane","Skill Drain","Tsukuyomi","Vampire Lord"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}