module.exports = {
    name: 'ejustice',
    description: "The test pack",
    cards: ["Destiny HERO - Diamond Dude","Destiny HERO - Dreadmaster","Dimensional Fissure","Elemental HERO Shining Phoenix Enforcer","Macro Cosmos","Voltanis the Adjudicator","Banisher of the Radiance","Clock Tower Prison","Destiny Signal","E - Emergency Call","Elemental HERO Phoenix Enforcer","Hero Flash!!","Icarus Attack","Majestic Mech - Goryu","R - Rightous Justice","Super-Electromagnet Voltech Dragon","Victory Viper XX03","Bountiful Artemis","Celestial Transformation","Cyber Gymnist","Cyber Phoenix","Destiny HERO - Captain Tenacious","Destiny HERO - Doom Lord","Destruction of Destiny","Elemental HERO Necroid Shaman","Elemental HERO Wild Wingman","Forced Back","Guard Penalty","H - Heated Heart","Herald of Green Light","Herald of Purple Light","Life Equalizer","Majestic Mech - Ohka","Miraculous Descent","O - Oversoul","Swift Birdman Joe","Avalanching Aussa","Batteryman D","Blazing Hiita","Cyber Kirin","Cyber Prima","Cyber Tutu","D - Shield","D - Time","Elemental Absorber","Elemental HERO Mariner","Elemental Recharge","Grand Convergence","Guard Dog","Harpie's Pet Baby Dragon","Layard the Liberator","Majestic Mech - Senku","Misfortune","Power Capsule","Raging Eria","Royal Knight","Searchlightman","Shattered Axe","Storming Wynn","Whirlwind Weasel"],
    common: ["Avalanching Aussa","Batteryman D","Blazing Hiita","Cyber Kirin","Cyber Prima","Cyber Tutu","D - Shield","D - Time","Elemental Absorber","Elemental HERO Mariner","Elemental Recharge","Grand Convergence","Guard Dog","Harpie's Pet Baby Dragon","Layard the Liberator","Majestic Mech - Senku","Misfortune","Power Capsule","Raging Eria","Royal Knight","Searchlightman","Shattered Axe","Storming Wynn","Whirlwind Weasel"],
    uncommon: ["Bountiful Artemis","Celestial Transformation","Cyber Gymnist","Cyber Phoenix","Destiny HERO - Captain Tenacious","Destiny HERO - Doom Lord","Destruction of Destiny","Elemental HERO Necroid Shaman","Elemental HERO Wild Wingman","Forced Back","Guard Penalty","H - Heated Heart","Herald of Green Light","Herald of Purple Light","Life Equalizer","Majestic Mech - Ohka","Miraculous Descent","O - Oversoul","Swift Birdman Joe"],
    rare: ["Banisher of the Radiance","Clock Tower Prison","Destiny Signal","E - Emergency Call","Elemental HERO Phoenix Enforcer","Hero Flash!!","Icarus Attack","Majestic Mech - Goryu","R - Rightous Justice","Super-Electromagnet Voltech Dragon","Victory Viper XX03"],
    epic: ["Destiny HERO - Diamond Dude","Destiny HERO - Dreadmaster","Dimensional Fissure","Elemental HERO Shining Phoenix Enforcer","Macro Cosmos","Voltanis the Adjudicator"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}