module.exports = {
    name: 'ichaos',
    description: "The test pack",
    cards: ["Black Luster Soldier - Envoy of the Beginning","Chaos Emperor Dragon - Envoy of the End","Dark Magician of Chaos","Dimension Fusion","Gren Maju Da Eiza","Invader of Darkness","Levia-Dragon - Daedalus","Manju of the Ten Thousand Hands","Manticore of Darkness","Black Tyranno","Chain Disappearance","Chaos End","Chaos Necromancer","Chaos Sorcerer","Compulsory Evacuation Device","Curse of Darkness","D.D. Designator","Dark Mirror Force","Dedication through Light and Darkness","DNA Transplant","Guardian Angel Joan","Primal Seed","Soul Absorption","Amphibious Bugroth MK-3","Balloon Lizard","Berserk Gorilla","Big Burn","Blasting the Ruins","Blazing Impachi","Cannonball Spear Shellfish","Chaos Greed","Chopman the Desperate Outlaw","Crimson Ninja","Cursed Seal of the Forbidden Spell","D.D. Scout Plane","Dark Driceratops","Des Kangaroo","Energy Drain","Enraged Battle Ox","Fenrir","Freed the Brave Warrior","Fuhma Shuriken","Getsu Fuhma","Gora Turtle of Illusion","Granadora","Heart of the Underdog","Inferno","Mad Dog of Darkness","Mataza the Zapper","Orca Mega-Fortress of Darkness","Prickle Fairy","Reload","Robbin' Zombie","Sacred Crane","Salvage","Self-Destruct Button","Smashing Ground","Stealth Bird","Stray Lambs","The Thing in the Crater","Ultra Evolution Pill","A Hero Emerges","Anti-Aircraft Flower","Begone, Knave!","Big Koala","Bowganian","Burning Algae","Chaosrider Gustaph","Coach Goblin","D.D. Borderline","Destruction Ring","Dimension Distortion","Don Turtle","Drillago","Earth Chant","Fiends Hand Mirror","Gale Lizard","Giga Gagagio","Gigantes","Gryphon's Fether Duster","Hyper Hammerhead","Insect Princess","Jade Insect Whistle","Lekunga","Lord Poison","Molten Zombie","Multiplication of Ants","Neo Bug","Ojama Black","Ojama Delta Hurricane!!","Ojama Yellow","Pinch Hopper","Recycle","Ryu Kokki","Sasuke Samurai #3","Sea Serpent Warrior of Darkness","Soul Tiger","Spatial Collapse","Spirit of the Pot of Greed","Strike Ninja","Stumbling","Terrorking Salmon","Thunder Crash","Torpedo Fish","Tower of Babel","Trap Jammer","Wild Nature's Release","Witch Doctor of Chaos","Yellow Luster Shield","Zero Gravity"],
    common: ["A Hero Emerges","Anti-Aircraft Flower","Begone, Knave!","Big Koala","Bowganian","Burning Algae","Chaosrider Gustaph","Coach Goblin","D.D. Borderline","Destruction Ring","Dimension Distortion","Don Turtle","Drillago","Earth Chant","Fiends Hand Mirror","Gale Lizard","Giga Gagagio","Gigantes","Gryphon's Fether Duster","Hyper Hammerhead","Insect Princess","Jade Insect Whistle","Lekunga","Lord Poison","Molten Zombie","Multiplication of Ants","Neo Bug","Ojama Black","Ojama Delta Hurricane!!","Ojama Yellow","Pinch Hopper","Recycle","Ryu Kokki","Sasuke Samurai #3","Sea Serpent Warrior of Darkness","Soul Tiger","Spatial Collapse","Spirit of the Pot of Greed","Strike Ninja","Stumbling","Terrorking Salmon","Thunder Crash","Torpedo Fish","Tower of Babel","Trap Jammer","Wild Nature's Release","Witch Doctor of Chaos","Yellow Luster Shield","Zero Gravity"],
    uncommon: ["Amphibious Bugroth MK-3","Balloon Lizard","Berserk Gorilla","Big Burn","Blasting the Ruins","Blazing Impachi","Cannonball Spear Shellfish","Chaos Greed","Chopman the Desperate Outlaw","Crimson Ninja","Cursed Seal of the Forbidden Spell","D.D. Scout Plane","Dark Driceratops","Des Kangaroo","Energy Drain","Enraged Battle Ox","Fenrir","Freed the Brave Warrior","Fuhma Shuriken","Getsu Fuhma","Gora Turtle of Illusion","Granadora","Heart of the Underdog","Inferno","Mad Dog of Darkness","Mataza the Zapper","Orca Mega-Fortress of Darkness","Prickle Fairy","Reload","Robbin' Zombie","Sacred Crane","Salvage","Self-Destruct Button","Smashing Ground","Stealth Bird","Stray Lambs","The Thing in the Crater","Ultra Evolution Pill"],
    rare: ["Black Tyranno","Chain Disappearance","Chaos End","Chaos Necromancer","Chaos Sorcerer","Compulsory Evacuation Device","Curse of Darkness","D.D. Designator","Dark Mirror Force","Dedication through Light and Darkness","DNA Transplant","Guardian Angel Joan","Primal Seed","Soul Absorption"],
    epic: ["Black Luster Soldier - Envoy of the Beginning","Chaos Emperor Dragon - Envoy of the End","Dark Magician of Chaos","Dimension Fusion","Gren Maju Da Eiza","Invader of Darkness","Levia-Dragon - Daedalus","Manju of the Ten Thousand Hands","Manticore of Darkness"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}