module.exports = {
    name: 'labnight',
    description: "The test pack",
    cards: ["Amazoness Archer","Bait Doll","Bio-Mage","Boneheimer","Crimson Sentry","Curse of the Masked Beast","Cyclon Laser","Deal of Phantom","Dragonic Attack","Dreamsprite","Earthbound Spirit","Ekibyo Drakmord","Fairy Guardian","Fire Sorcerer","Flame Dancer","Flying Fish","Gadget Soldier","Grand Tiki Elder","Graverobber's Retribution","Headless Knight","Infinite Cards","Lady Panther","Lightning Blade","Lightning Conger","Maryokutai","Mask of Weakness","Melchid the Four-Faced Beast","Miricle Dig","Return of the Doomed","Riryoku Field","Scroll of Bewitchment","Spherous Lady","Spirit Elimination","Summoner of Illusions","Supply","Swordsman of Landstar","The Dark Door","The Emperor's Holiday","The Gross Ghost of Fled Dreams","The Portrait's Secret","The Rock Spirit","The Unfriendly Amazon","Tornado Bird","Vengeful Bog Spirit","Worm Drake","Amphibian Beast","Aqua Spirit","Chosen One","Collected Power","Cure Mermaid","Dancing Fairy","Darklord Marie","De-Fusion","Destruction Punch","Empress Mantis","Fusion Gate","Garuda the Wind Spirit","Humanoid Slime","Hysteric Fairy","Jam Defender","Jowgen the Spiritualist","Lady Assailant of Flames","Mask of Brutality","Nuvia the Wicked","Shining Abyss","Skull Lair","Soul of Purity and Light","Spirit Message \"A\"","Spirit Message \"I\"","Spirit Message \"L\"","Spirit Message \"N\"","Spirit of Flames","Spirit of the Breeze","The Earl of Demise","The Forgiving Maiden","Tornado Wall","Zombyra the Dark","Bazoo the Soul Eater","Dark Spirit of the Silent","Destiny Board","Fairy Box","Fire Princess","Gilasaurus","Humanoid Worm Drake","Jam Breeding Machine","Jar of Greed","Kycoo the Ghost Destroyer","Magic Cylinder","Mask of Dispel","Mask of the Accursed","Offerings to the Doomed","Revival Jam","Royal Command","Spiritualism","St. Joan","The Masked Beast","Card of Safe Return","Dark Necrofear","Gemini Elf","Mage Power","Mask of Restrict","The Last Warrior from Another Planet","Torrential Tribute","United We Stand"],
    common: ["Amazoness Archer","Bait Doll","Bio-Mage","Boneheimer","Crimson Sentry","Curse of the Masked Beast","Cyclon Laser","Deal of Phantom","Dragonic Attack","Dreamsprite","Earthbound Spirit","Ekibyo Drakmord","Fairy Guardian","Fire Sorcerer","Flame Dancer","Flying Fish","Gadget Soldier","Grand Tiki Elder","Graverobber's Retribution","Headless Knight","Infinite Cards","Lady Panther","Lightning Blade","Lightning Conger","Maryokutai","Mask of Weakness","Melchid the Four-Faced Beast","Miricle Dig","Return of the Doomed","Riryoku Field","Scroll of Bewitchment","Spherous Lady","Spirit Elimination","Summoner of Illusions","Supply","Swordsman of Landstar","The Dark Door","The Emperor's Holiday","The Gross Ghost of Fled Dreams","The Portrait's Secret","The Rock Spirit","The Unfriendly Amazon","Tornado Bird","Vengeful Bog Spirit","Worm Drake"],
    uncommon: ["Amphibian Beast","Aqua Spirit","Chosen One","Collected Power","Cure Mermaid","Dancing Fairy","Darklord Marie","De-Fusion","Destruction Punch","Empress Mantis","Fusion Gate","Garuda the Wind Spirit","Humanoid Slime","Hysteric Fairy","Jam Defender","Jowgen the Spiritualist","Lady Assailant of Flames","Mask of Brutality","Nuvia the Wicked","Shining Abyss","Skull Lair","Soul of Purity and Light","Spirit Message 'A'","Spirit Message 'I'","Spirit Message 'L'","Spirit Message 'N'","Spirit of Flames","Spirit of the Breeze","The Earl of Demise","The Forgiving Maiden","Tornado Wall","Zombyra the Dark"],
    rare: ["Bazoo the Soul Eater","Dark Spirit of the Silent","Destiny Board","Fairy Box","Fire Princess","Gilasaurus","Humanoid Worm Drake","Jam Breeding Machine","Jar of Greed","Magic Cylinder","Mask of Dispel","Mask of the Accursed","Offerings to the Doomed","Revival Jam","Royal Command","Spiritualism","St. Joan","The Masked Beast"],
    epic: ["Card of Safe Return","Dark Necrofear","Gemini Elf","Kycoo the Ghost Destroyer","Mage Power","Mask of Restrict","The Last Warrior from Another Planet","Torrential Tribute","United We Stand"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}