module.exports = {
    name: 'ldarkness',
    description: "The test pack",
    cards: ["A Feint Plan","After the Struggle","Bark of Dark Ruler","Blast with Chain","Bubble Crash","Burst Breath","Cave Dragon","Convulsion of Nature","Disappear","Double Snare","Dragon Manipulator","Dargon's Gunfire","Emergency Provisions","Fatal Abacus","Fengshen Mirror","Frontier Wiseman","Fushi No Tori","Gradius' Option","Gray Wing","Great Long Nose","Heart of Clear Water","Lesser Fiend","Life Absorbing Machine","Lizard Soldier","Magic Reflector","Mysterious Guard","Otohime","Possessed Dark Soul","Robolady","Robotic Knight","Roboyarou","Ryu-Kishin Clown","Serpentine Princess","Shadow Tamer","Skull Knight #2","Smoke Grenade of the Theif","Soul Demolition","Spirit Ryu","Spring of Rebirth","The Dragon Swelling in the Cave","The Dragon's Bead","The Hunter With 7 Weapons","The Illusory Gentleman","The Secret of the Bandit","Throwstone Unit","Twin-Headed Wolf","Winged Minion","Wolf Axewielder","Woodland Sprite","A Wingbeat of Giant Dragon","Airknight Parshath","Array of Revealing Light","Dark Balter the Terrible","Dragon's Rage","Drop Off","Exiled Force","Fiend Skull Dragon","Inaba White Rabbit","Last Turn","Luster Dragon #2","Maharaghi","Nutrient Z","Ominous Fortunetelling","Opticlops","Ready for Intercepting","Ryu Senshi","Second Coin Toss","Spear Dragon","Spirit's Invitation","Spiritual Energy Settle Machine","Super Robolady","Super Roboyarou","Susa Soldier","The A. Forces","The Puppet Magic of Dark Ruler","Troop Dragon","Warrior Dai Grepher","A Legendary Ocean","Asura Priest","Bad Reaction to Simochi","Creature Swap","Dark Ruler Ha Des","Freed the Matchless General","Fusion Sword Murasame Blade","Hino-Kagu Tsuchi","Injection Fairy Lily","Patrician of Darkness","Royal Oppression","Stamping Destruction","Super Rejuvenation","The Warrior Returning Alive","Thunder Nyan Nyan","Twin-Headed Behemoth","Bottomless Trap Hole","Fiber Jar","Marauding Captain","Reinforcement of the Army","Tyrant Dragon","Yamata Dragon","Yata-Garasu"],
    common: ["A Feint Plan","After the Struggle","Bark of Dark Ruler","Blast with Chain","Bubble Crash","Burst Breath","Cave Dragon","Convulsion of Nature","Disappear","Double Snare","Dragon Manipulator","Dargon's Gunfire","Emergency Provisions","Fatal Abacus","Fengshen Mirror","Frontier Wiseman","Fushi No Tori","Gradius' Option","Gray Wing","Great Long Nose","Heart of Clear Water","Lesser Fiend","Life Absorbing Machine","Lizard Soldier","Magic Reflector","Mysterious Guard","Otohime","Possessed Dark Soul","Robolady","Robotic Knight","Roboyarou","Ryu-Kishin Clown","Serpentine Princess","Shadow Tamer","Skull Knight #2","Smoke Grenade of the Theif","Soul Demolition","Spirit Ryu","Spring of Rebirth","The Dragon Swelling in the Cave","The Dragon's Bead","The Hunter With 7 Weapons","The Illusory Gentleman","The Secret of the Bandit","Throwstone Unit","Twin-Headed Wolf","Winged Minion","Wolf Axewielder","Woodland Sprite"],
    uncommon: ["A Wingbeat of Giant Dragon","Airknight Parshath","Array of Revealing Light","Dark Balter the Terrible","Dragon's Rage","Drop Off","Exiled Force","Fiend Skull Dragon","Inaba White Rabbit","Last Turn","Luster Dragon #2","Maharaghi","Nutrient Z","Ominous Fortunetelling","Opticlops","Ready for Intercepting","Ryu Senshi","Second Coin Toss","Spear Dragon","Spirit's Invitation","Spiritual Energy Settle Machine","Super Robolady","Super Roboyarou","Susa Soldier","The A. Forces","The Puppet Magic of Dark Ruler","Troop Dragon","Warrior Dai Grepher"],
    rare: ["A Legendary Ocean","Asura Priest","Bad Reaction to Simochi","Creature Swap","Dark Ruler Ha Des","Freed the Matchless General","Fusion Sword Murasame Blade","Hino-Kagu Tsuchi","Injection Fairy Lily","Patrician of Darkness","Royal Oppression","Stamping Destruction","Super Rejuvenation","The Warrior Returning Alive","Thunder Nyan Nyan","Twin-Headed Behemoth"],
    epic: ["Bottomless Trap Hole","Fiber Jar","Marauding Captain","Reinforcement of the Army","Tyrant Dragon","Yamata Dragon","Yata-Garasu"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}