module.exports = {
    name: 'magicforce',
    description: "The test pack",
    cards: ["Amazoness Swords Woman","Breaker the Magical Warrior","Dark Magician Girl","Dark Paladin","Diffusion Wave-Motion","Kaiser Colosseum","Luster Dragon","Magical Scientist","Mass Driver","Royal Magical Library","Skilled Dark Magician","Spell Canceller","XYZ-Dragon Cannon","Amazoness Spellcaster","Amazoness Tiger","Apprentice Magician","Autonomous Action Unit","Big Bang Shot","Chaos Command Magician","Dark Core","Dark Scorpion - Cliff the trap Remover","Des Koala","Dimension Jar","Double Spell","Giant Orc","Magical Marionette","Magical Merchant","My Body as a Shield","Old Vindictive Magician","Paladin of White Dragon","Rivalry of Warlords","Skilled White Magician","Tribe-Infecting Virus","Ultimate Obedient Fiend","Amazoness Archers","Amazoness Blowpiper","Amazoness Fighter","Amazoness Paladin","Combination Attack","D.D Crazy Beast","Dark Blade","Decayed Commander","Disarmament","Dramatic Rescue","Emblem of Dragon Destroyer","Frontline Base","Great Angus","Great Phantom Theif","Helping Robo for Combat","Kiryu","Mega Ton Magical Cannon","Pitch-Black Power Stone","Pitch-Dark Dragon","Poison of the Old Man","Roulette Barrel","Secret Barrel","Sonic Duck","Spell Shield Type-8","Spellbook Organization","Tribute Doll","Wave-Motion Cannon","XY-Dragon Cannon","XZ-Tank Cannon","YZ-Tank Dragon","Adhesion Trap Hole","Aitsu","Ante","Anti-Spell","Armor Exe","Burning Beast","Cat's Ear Tribe","Continuous Destruction Punch","Dark Cat with White Tail","Demotion","Des Dendle","Exhausting Spell","Formation Union","Freezing Beast","Gather Your Mind","Hidden Spellbook","Huge Revolution","Jar Robber","Kishido Spirit","Koitsu","Magical Plant Mandragola","Metalsilver Armor","Meteorain","Miracle Restoring","Neko Mane King","Oppressed People","People Running About","Physical Double","Pinapple Blast","Pixie Knight","Raregold Armor","Remove Brainwashing","Second Goblin","Senri Eye","The Spell Absorbing Life","Thunder of Ruler","Union Rider","United Resistance","Vampiric Orchis","White Dragon Ritual","X- Head Cannon","Y-Dragon Head","Z-Metal Tank","Zombie Tiger"],
    common: ["Adhesion Trap Hole","Aitsu","Ante","Anti-Spell","Armor Exe","Burning Beast","Cat's Ear Tribe","Continuous Destruction Punch","Dark Cat with White Tail","Demotion","Des Dendle","Exhausting Spell","Formation Union","Freezing Beast","Gather Your Mind","Hidden Spellbook","Huge Revolution","Jar Robber","Kishido Spirit","Koitsu","Magical Plant Mandragola","Metalsilver Armor","Meteorain","Miracle Restoring","Neko Mane King","Oppressed People","People Running About","Physical Double","Pinapple Blast","Pixie Knight","Raregold Armor","Remove Brainwashing","Second Goblin","Senri Eye","The Spell Absorbing Life","Thunder of Ruler","Union Rider","United Resistance","Vampiric Orchis","White Dragon Ritual","X- Head Cannon","Y-Dragon Head","Z-Metal Tank","Zombie Tiger"],
    uncommon: ["Amazoness Archers","Amazoness Blowpiper","Amazoness Fighter","Amazoness Paladin","Combination Attack","D.D Crazy Beast","Dark Blade","Decayed Commander","Disarmament","Dramatic Rescue","Emblem of Dragon Destroyer","Frontline Base","Great Angus","Great Phantom Theif","Helping Robo for Combat","Kiryu","Mega Ton Magical Cannon","Pitch-Black Power Stone","Pitch-Dark Dragon","Poison of the Old Man","Roulette Barrel","Secret Barrel","Sonic Duck","Spell Shield Type-8","Spellbook Organization","Tribute Doll","Wave-Motion Cannon","XY-Dragon Cannon","XZ-Tank Cannon","YZ-Tank Dragon"],
    rare: ["Amazoness Spellcaster","Amazoness Tiger","Apprentice Magician","Autonomous Action Unit","Big Bang Shot","Chaos Command Magician","Dark Core","Dark Scorpion - Cliff the trap Remover","Des Koala","Dimension Jar","Double Spell","Giant Orc","Magical Marionette","Magical Merchant","My Body as a Shield","Old Vindictive Magician","Paladin of White Dragon","Rivalry of Warlords","Skilled White Magician","Tribe-Infecting Virus","Ultimate Obedient Fiend"],
    epic: ["Amazoness Swords Woman","Breaker the Magical Warrior","Dark Magician Girl","Dark Paladin","Diffusion Wave-Motion","Kaiser Colosseum","Luster Dragon","Magical Scientist","Mass Driver","Royal Magical Library","Skilled Dark Magician","Spell Canceller","XYZ-Dragon Cannon"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}