module.exports = {
    name: 'magicruler',
    description: "The test pack",
    cards: ["Ameba","Ancient One of the Deep Forest","Black Illusion Ritual","Black Pendant","Boar Soldier","Ceremonial Bell","Commencement Dance","Dark Witch","Dark Zebra","Darkness Approaches","Eatgaboon","Electric Snake","Eternal Rest","Fairy's Hand Mirror","Fire Kraken","Flash Assailant","Giant Turtle Who Feeds on Flames","Griggle","Guardian of the Throne Room","Hamburger Recipe","High Tide Gyojin","Hiro's Shadow Scout","Horn of Light","Horn of the Unicorn","House of Adhesive Tape","Invader of the Throne","Jigen Bakudan","Karate Man","Kotodama","Labyrinth Wall","Liquid Beast","Magical Labyrinth","Mechanical Snail","Metal Fish","Minar","Octoberser","Peacock","Penguin Knight","Performance of Sword","Psychic Kappa","Queen Bird","Red Archery Girl","Senju of the Thousand Hands","Snake Fang","Sonic Bird","Spear Cretin","Stone Ogre Grotto","Tailor of the Fickle","The Reliable Guardian","Turtle Oath","Twin Long Rods #2","Tyhone #2","Wall Shadow","Weather Report","Whiptail Crow","Banisher of the Light","Chain Energy","Chorus of Sanctuary","Crab Turtle","Curse of Fiend","Final Destiny","Flying Kamakiri #1","Gaia Power","Giant Germ","Giant Rat","Gravekeeper's Servant","Hungry Burger","Hyozanryu","Luminous Spark","Malevolent Nuzzler","Manga Ryu-Ran","Messenger of Peace","Molten Destruction","Mother Grizzly","Mystic Plasma Zone","Mystic Tomato","Nimble Momonga","Painful Choice","Rising Air Current","Rush Recklessly","Ryu-Ran","Serpent Night Dragon","Shining Angel","Spellbinding Circle","Toll","Toon Mermaid","UFO Turtle","Umiiruka","Upstart Goblin","Blue-Eyes Toon Dragon","Giant Trunade","Maha Vailo","Megamorph","Mystical Space Typhoon","Relinquished","Slot Machine","Toon World","Axe of Despair","Confiscation","Cyber Jar","Delinquent Duo","Snatch Steal","The Forceful Sentry","Toon Summoned Skull"],
    common: ["Ameba","Ancient One of the Deep Forest","Black Illusion Ritual","Black Pendant","Boar Soldier","Ceremonial Bell","Commencement Dance","Dark Witch","Dark Zebra","Darkness Approaches","Eatgaboon","Electric Snake","Eternal Rest","Fairy's Hand Mirror","Fire Kraken","Flash Assailant","Giant Turtle Who Feeds on Flames","Griggle","Guardian of the Throne Room","Hamburger Recipe","High Tide Gyojin","Hiro's Shadow Scout","Horn of Light","Horn of the Unicorn","House of Adhesive Tape","Invader of the Throne","Jigen Bakudan","Karate Man","Kotodama","Liquid Beast","Magical Labyrinth","Mechanical Snail","Metal Fish","Minar","Octoberser","Peacock","Penguin Knight","Performance of Sword","Psychic Kappa","Queen Bird","Red Archery Girl","Snake Fang","Spear Cretin","Stone Ogre Grotto","Tailor of the Fickle","The Reliable Guardian","Turtle Oath","Twin Long Rods #2","Tyhone #2","Wall Shadow","Weather Report","Whiptail Crow"],
    uncommon: ["Banisher of the Light","Sonic Bird","Slot Machine","Chain Energy","Chorus of Sanctuary","Crab Turtle","Curse of Fiend","Final Destiny","Flying Kamakiri #1","Gaia Power","Giant Germ","Giant Rat","Gravekeeper's Servant","Hungry Burger","Hyozanryu","Luminous Spark","Malevolent Nuzzler","Manga Ryu-Ran","Molten Destruction","Mother Grizzly","Mystic Plasma Zone","Senju of the Thousand Hands","Mystic Tomato","Nimble Momonga","Rising Air Current","Rush Recklessly","Ryu-Ran","Serpent Night Dragon","Shining Angel","Spellbinding Circle","Toll","Labyrinth Wall","Toon Mermaid","UFO Turtle","Umiiruka"],
    rare: ["Blue-Eyes Toon Dragon","Giant Trunade","Messenger of Peace","Maha Vailo","Megamorph","Mystical Space Typhoon","Painful Choice","Relinquished","Toon World","Upstart Goblin"],
    epic: ["Axe of Despair","Confiscation","Cyber Jar","Delinquent Duo","Snatch Steal","The Forceful Sentry","Toon Summoned Skull"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}