module.exports = {
    name: 'pguardian',
    description: "The test pack",
    cards: ["8-Claws Scorpion","An Owl of Luck","Bottomless Shifiting Sands","Buster Rancher","Card Shuffle","Cobraman Sakuzy","Curse of Aging","Curse of Royal","Dark Designator","Dark Snake Syndrome","Distirbance Strategy","Great Axe Mummy","Gora Turtle","Gravekeeper's Chief","Gravekeeper's Curse","Gravekeeper's Vassal","Gravekeeper's Watcher","Hieroglyph Lithograph","Kryuel","Molten Behemoth","Nightmare Horse","Non Aggression Area","Ordeal of a Traveler","Pharaoh's Treasure","Poison Mummy","Pyramid Energy","Pyro Clock of Destiny","Reaper on the Nightmare","Reckless Greed","Reversal Quiz","Rope of Life","Royal Keeper","Secret Pass to the Treasure","Servant of Catabolism","Shapesnatch","Souleater","Swarm of Locusts","Swarm of Scarabs","Timeater","Timidity","Trap of Board Eraser","Tutan Mask","Wandering Mummy","Winged Sage Falcos","Yomi Ship","A Cat of Ill Omen","A Man With Wdjat","Arsenal Bug","Banner of Courage","Barrel Behind the Door","Charm of Shabti","Cobra Jar","D. Tribe","Dark Coffin","Dark Room of Nightmares","Dark Scorpion Burglars","Des Lacoda","Gravekeeper's Assailant","Gravekeeper's Cannonholder","Helpoemer","Inpachi","Jowls of Dark Demise","Maiden of the Aqua","Moisture Creature","Mucus Yolk","Narrow Pass","Needle Ceiling","Raigeki Break","Sasuke Samurai","Spirit Reaper","Statue of the Wicked","Birdface","Book of Taiyou","Byser Shock","Call of the Mummy","Coffin Seller","Dark Dust Spirit","Dark Jeroid","Dice jar","Different Dimension Capsule","Don Zaloog","Fushioh Richie","Gravekeeper's Spear Soldier","Great Dezard","Guardian Sphinx","Kabazauls","Master Kyonshee","Mystical Knight of Jackal","Needle Wall","Newdoria","Nightmare Wheel","Pyramid Turtle","Question","Rite of Spirit","Royal Tribute","Terraforming","Book of Life","Book of Moon","Gravekeeper's Guard","Gravekeeper's Spy","King Tiger Wanghu","Lava Golem","Metamorphosis","Mirage of Nightmare","Necrovalley","Reasoning","Ring of Destruction","Trap Dustshoot"],
    common: ["8-Claws Scorpion","An Owl of Luck","Bottomless Shifiting Sands","Buster Rancher","Card Shuffle","Cobraman Sakuzy","Curse of Aging","Curse of Royal","Dark Designator","Dark Snake Syndrome","Distirbance Strategy","Great Axe Mummy","Gora Turtle","Gravekeeper's Chief","Gravekeeper's Curse","Gravekeeper's Vassal","Gravekeeper's Watcher","Hieroglyph Lithograph","Kryuel","Molten Behemoth","Nightmare Horse","Non Aggression Area","Ordeal of a Traveler","Pharaoh's Treasure","Poison Mummy","Pyramid Energy","Pyro Clock of Destiny","Reaper on the Nightmare","Reckless Greed","Reversal Quiz","Rope of Life","Royal Keeper","Secret Pass to the Treasure","Servant of Catabolism","Shapesnatch","Souleater","Swarm of Locusts","Swarm of Scarabs","Timeater","Timidity","Trap of Board Eraser","Tutan Mask","Wandering Mummy","Winged Sage Falcos","Yomi Ship"],
    uncommon: ["A Cat of Ill Omen","A Man With Wdjat","Arsenal Bug","Banner of Courage","Barrel Behind the Door","Charm of Shabti","Cobra Jar","D. Tribe","Dark Coffin","Dark Room of Nightmares","Dark Scorpion Burglars","Des Lacoda","Gravekeeper's Assailant","Gravekeeper's Cannonholder","Helpoemer","Inpachi","Jowls of Dark Demise","Maiden of the Aqua","Moisture Creature","Mucus Yolk","Narrow Pass","Needle Ceiling","Raigeki Break","Sasuke Samurai","Spirit Reaper","Statue of the Wicked"],
    rare: ["Birdface","Book of Taiyou","Byser Shock","Call of the Mummy","Coffin Seller","Dark Dust Spirit","Dark Jeroid","Dice jar","Different Dimension Capsule","Don Zaloog","Fushioh Richie","Gravekeeper's Spear Soldier","Great Dezard","Guardian Sphinx","Kabazauls","Master Kyonshee","Mystical Knight of Jackal","Needle Wall","Newdoria","Nightmare Wheel","Pyramid Turtle","Question","Rite of Spirit","Royal Tribute","Terraforming"],
    epic: ["Book of Life","Book of Moon","Gravekeeper's Guard","Gravekeeper's Spy","King Tiger Wanghu","Lava Golem","Metamorphosis","Mirage of Nightmare","Necrovalley","Reasoning","Ring of Destruction","Trap Dustshoot"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}