module.exports = {
    name: 'pservant',
    description: "The test pack",
    cards: ["7 Completed","Armored Glass","Attack and Receive","Bite Shoes","Bombardment Beetle","Cyber Falcon","Dark Bat","Deepsea Warrior","Dimensionhole","Dokuroyaiba","Drill Bug","Earthshaker","Enchanted Javelin","Flying Kamakiri #2","Gamble","Gift of The Mystical Elf","Girochin Kuwagata","Gradius","Ground Collapse","Gust","Infinite Dismissal","Insect Barrier","Insect Imitation","Inspection","Invatation to a Deep Sleep","Island Turtle","Kiseitai","Light of Intervention","Lightforce Sword","Magical Hats","Major Riot","Metal Detector","Minor Goblin Official","Mr. Volcano","Mystic Probe","Numinous Healer","Oni Tank T-34","Rain of Mercy","Respect Play","Science Soldier","Shadow of Eyes","Shift","Skull Mariner","Solemn Wishes","Solomon's Lawbook","Souls of the Forgotten","Spikebot","Steel Ogre Grotto #2","The All-Seeing White Tiger","The Eye of Truth","Thousand-Eyes Idol","Three-Headed Geedo","Type Zero Magic Crusher","Vampire Baby","World Suppression","Appropriate","Bubonic Vermin","Burning Land","Darkfire Soldier #1","Darkfire Soldier #2","Driving Snow","Fairy Meteor Crush","Flame Champion","Forced Requisition","Gearfried the Iron Knight","Graverobber","Gravity Bind","Hayabusa Knight","Mad Sword Beast","Michizure","Monster Recovery","Parasite Paracide","Skull Invitation","Sky Scout","Sword Hunter","The Regulation of Tribe","Twin-Headed Fire Dragon","Time Seal","Backup Soldier","Beast of Talwar","Buster Blader","Ceasefire","DNA Surgery","Dust Tornado","Goblin Attack Force","Limiter Removal","Mirror Wall","Morphing Jar #2","Nobleman of Crossout","Nobleman of Extermination","Prohibition","The Legendary Fisherman","Thousand-Eyes Restrict","Wingweaver","Call of the Haunted","Chain Destruction","Cold Wave","Imperial Order","Jinzo","Magic Drain","Premature Burial","The Fiend Megacyber","The Shallow Grave"],
    common: ["7 Completed","Armored Glass","Attack and Receive","Bite Shoes","Bombardment Beetle","Cyber Falcon","Dark Bat","Deepsea Warrior","Dimensionhole","Dokuroyaiba","Drill Bug","Earthshaker","Enchanted Javelin","Flying Kamakiri #2","Gamble","Gift of The Mystical Elf","Girochin Kuwagata","Gradius","Ground Collapse","Gust","Infinite Dismissal","Insect Barrier","Insect Imitation","Inspection","Invatation to a Deep Sleep","Island Turtle","Kiseitai","Light of Intervention","Lightforce Sword","Magical Hats","Major Riot","Metal Detector","Minor Goblin Official","Mr. Volcano","Mystic Probe","Numinous Healer","Oni Tank T-34","Rain of Mercy","Respect Play","Science Soldier","Shadow of Eyes","Shift","Skull Mariner","Solemn Wishes","Solomon's Lawbook","Souls of the Forgotten","Spikebot","Steel Ogre Grotto #2","The All-Seeing White Tiger","The Eye of Truth","Thousand-Eyes Idol","Three-Headed Geedo","Type Zero Magic Crusher","Vampire Baby","World Suppression"],
    uncommon: ["Appropriate","Bubonic Vermin","Burning Land","Darkfire Soldier #1","Darkfire Soldier #2","Driving Snow","Fairy Meteor Crush","Flame Champion","Forced Requisition","Gearfried the Iron Knight","Graverobber","Gravity Bind","Hayabusa Knight","Mad Sword Beast","Michizure","Monster Recovery","Parasite Paracide","Skull Invitation","Sky Scout","Sword Hunter","The Regulation of Tribe","Twin-Headed Fire Dragon","Time Seal"],
    rare: ["Backup Soldier","Beast of Talwar","Buster Blader","Ceasefire","DNA Surgery","Dust Tornado","Goblin Attack Force","Limiter Removal","Mirror Wall","Morphing Jar #2","Nobleman of Crossout","Nobleman of Extermination","Prohibition","The Legendary Fisherman","The Shallow Grave","Thousand-Eyes Restrict","Wingweaver"],
    epic: ["Call of the Haunted","Chain Destruction","Cold Wave","Imperial Order","Jinzo","Magic Drain","Premature Burial","The Fiend Megacyber"],
    price: 100,
    commonnum: 3,
    uncommonnum: 2,
    rarenum: 1,
    epicnum: 1,
}