module.exports = {
    name: 'tourney1',
    description: "The test pack",
    cards: ["Black Luster Soldier - Envoy of the Beginning","Chaos Sorcerer","Zaborg the Thunder Monarch","Cyber Dragon","Breaker the Magical Warrior","D.D. Warrior Lady","Mystic Tomato","Shining Angel","Tsukuyomi","Witch of the Black Forest","Exiled Force","Sangan","Spirit Reaper","Magician of Faith","Raigeki","Confiscation","Harpie's Feather Duster","Polymerization","Creature Swap","Reinforcement of the Army","Pot of Greed","Nobleman of Crossout","Last Will","Smashing Ground","Mystical Space Typhoon","Book of Moon","Scapegoat","Enemy Controller","Snatch Steal","Mirror Force","Torrential Tribute","Royal Decree","Cyber End Dragon","Jinzo","Cyber Twin Dragon","Great Maju Garzett","Goblin Attack Force","Indomitable Fighter Lei Lei","Goblin Elite Attack Force","Skilled Dark Magician","Kycoo the Ghost Destroyer","The Forceful Sentry","Cold Wave","United We Stand","Premature Burial","Phoenix Wing Wind Blast","Final Attack Orders","Ultimate Offering","Skill Drain","Call of the Haunted","Solemn Judgment","Royal Oppression","Luster Dragon","Gemini Elf","Skull Archfiend of Lightning","Reflect Bounder","Heavy Storm","Swords of Revealing Light","Kaiser Colosseum","Magic Drain","Chaos Emperor Dragon - Envoy of the End","Hydrogeddon","Tribe-Infecting Virus","Old Vindictive Magician","Magical Merchant","Monster Reborn","Trap Hole","Bottomless Trap Hole","Compulsory Evacuation Device","UFOroid Fighter","Elemental HERO Wildedge","Elemental HERO Shining Flare Wingman","Gaia the Dragon Champion","Steam Gyroid","Elemental HERO Rampart Blaster","Flame Swordsman","Flame Ghost","Wall of Illusion","White Magical Hat","Axe of Despair","Sakuretsu Armor","Mirror Wall"],
    epic: ["Black Luster Soldier - Envoy of the Beginning","Chaos Sorcerer","Zaborg the Thunder Monarch","Cyber Dragon","Breaker the Magical Warrior","D.D. Warrior Lady","Mystic Tomato","Shining Angel","Tsukuyomi","Witch of the Black Forest","Exiled Force","Sangan","Spirit Reaper","Magician of Faith","Raigeki","Confiscation","Harpie's Feather Duster","Polymerization","Creature Swap","Reinforcement of the Army","Pot of Greed","Nobleman of Crossout","Last Will","Smashing Ground","Mystical Space Typhoon","Book of Moon","Scapegoat","Enemy Controller","Snatch Steal","Mirror Force","Torrential Tribute","Royal Decree","Cyber End Dragon","Jinzo","Cyber Twin Dragon","Great Maju Garzett","Goblin Attack Force","Indomitable Fighter Lei Lei","Goblin Elite Attack Force","Skilled Dark Magician","Kycoo the Ghost Destroyer","The Forceful Sentry","Cold Wave","United We Stand","Premature Burial","Phoenix Wing Wind Blast","Final Attack Orders","Ultimate Offering","Skill Drain","Call of the Haunted","Solemn Judgment","Royal Oppression","Luster Dragon","Gemini Elf","Skull Archfiend of Lightning","Reflect Bounder","Heavy Storm","Swords of Revealing Light","Kaiser Colosseum","Magic Drain","Chaos Emperor Dragon - Envoy of the End","Hydrogeddon","Tribe-Infecting Virus","Old Vindictive Magician","Magical Merchant","Monster Reborn","Trap Hole","Bottomless Trap Hole","Compulsory Evacuation Device","UFOroid Fighter","Elemental HERO Wildedge","Elemental HERO Shining Flare Wingman","Gaia the Dragon Champion","Steam Gyroid","Elemental HERO Rampart Blaster","Flame Swordsman","Flame Ghost","Wall of Illusion","White Magical Hat","Axe of Despair","Sakuretsu Armor","Mirror Wall"],
    price: 250,
    epicnum: 4,
}

